### ISSUE TITLE
[Bug]: Butterflies In Every Creative Tab

### ISSUE THREAD

**Issue by RyanSalad** [crispytwig/Naturalist#5]
### Mod Version

4.0.1

### Mod Loader

Fabric

### Mod Loader Version

0.14.24

### What happened?

All the variants of butterflies are being placed in every mod's creative tabs.
![2023-11-01_10 28 31](https://github.com/starfish-studios/Naturalist/assets/130966747/8a068af6-9274-4a3f-ad91-9e9753839312)
![2023-11-01_10 17 14](https://github.com/starfish-studios/Naturalist/assets/130966747/13645a59-03d4-415c-b5c8-34c55988047e)

### latest.log

[latest.log](https://github.com/starfish-studios/Naturalist/files/13228798/latest.log)

**Comment by Abrams11IsBack** [comment]
got the same issue here, forge 43.3.2 1.19.2

**Comment by PianoManu** [comment]
Same issue in a custom modpack (Forge 43.2.23 and Naturalist 4.0.1)

**Comment by DEAFG0AT** [comment]
I'm having the same problem on Fabric 1.19.2. It's appending the butterflies but forgets to check for the item group

**Comment by Rimevel** [comment]
Also getting this in my forge modpack. Using latest verson of the mod.

**Comment by RyanSalad** [comment]
>A butterfly also appears over the "Delete Item" button in the Creative inventory

Yeah I noticed this too, and am also on 1.19.2
